import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ensureLlmConfig } from "./config.js";
import { claudeHookWrapperPath, claudeSettingsPath } from "./paths.js";

/** Hook events the guard registers (enforce set only — see claude-hook.ts). */
const CLAUDE_HOOK_EVENTS = ["UserPromptSubmit", "PreToolUse"] as const;

function isLlmBudgetEntry(entry: unknown): boolean {
  return (
    typeof entry === "object" &&
    entry !== null &&
    "command" in entry &&
    String((entry as { command: unknown }).command).includes("llm-budget")
  );
}

interface ClaudeHookGroup {
  matcher?: string;
  hooks: Array<Record<string, unknown>>;
}

/**
 * Register the guard into `~/.claude/settings.json`.
 *
 * settings.json holds unrelated user config, so this merges carefully: only
 * `hooks.<event>` lists gain (or keep) one entry whose command references
 * llm-budget. Everything else is preserved verbatim.
 */
export function installClaudeHooks(home = homedir()): string {
  ensureLlmConfig(home);
  const wrapper = claudeHookWrapperPath(home);
  const settingsPath = claudeSettingsPath(home);
  const cli = join(fileURLToPath(new URL("./cli.js", import.meta.url)));

  mkdirSync(dirname(wrapper), { recursive: true });
  writeFileSync(
    wrapper,
    `#!/bin/bash
NODE="$(command -v node 2>/dev/null || true)"
if [ -z "$NODE" ]; then
  for candidate in "$HOME/.vite-plus/bin/node" /usr/bin/node /usr/local/bin/node; do
    if [ -x "$candidate" ]; then
      NODE="$candidate"
      break
    fi
  done
fi
if [ -z "$NODE" ]; then
  # Fail closed: without node we cannot evaluate, so block with instructions.
  echo "llm-budget: node not found; cannot check budget" >&2
  exit 2
fi
exec "$NODE" ${JSON.stringify(cli)} claude hook
`,
  );
  chmodSync(wrapper, 0o755);

  let settings: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    settings = JSON.parse(readFileSync(settingsPath, "utf8")) as Record<string, unknown>;
  }
  const hooks =
    typeof settings.hooks === "object" && settings.hooks !== null
      ? (settings.hooks as Record<string, unknown>)
      : {};

  for (const event of CLAUDE_HOOK_EVENTS) {
    const groups = Array.isArray(hooks[event]) ? (hooks[event] as ClaudeHookGroup[]) : [];
    const already = groups.some((group) => (group?.hooks ?? []).some(isLlmBudgetEntry));
    if (!already) {
      const group: ClaudeHookGroup = { hooks: [{ type: "command", command: wrapper }] };
      if (event === "PreToolUse") group.matcher = "*";
      groups.push(group);
    }
    hooks[event] = groups;
  }
  settings.hooks = hooks;

  mkdirSync(dirname(settingsPath), { recursive: true });
  writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  return [
    "Installed llm-budget Claude Code hooks (fail-closed)",
    `  ${settingsPath}`,
    `  ${wrapper}`,
    "",
    "Restart any running Claude Code sessions so they pick up settings.json.",
  ].join("\n");
}

export function uninstallClaudeHooks(home = homedir()): string {
  const wrapper = claudeHookWrapperPath(home);
  const settingsPath = claudeSettingsPath(home);

  let removedFrom = "";
  if (existsSync(settingsPath)) {
    const settings = JSON.parse(readFileSync(settingsPath, "utf8")) as Record<
      string,
      unknown
    >;
    const hooks = settings.hooks;
    if (typeof hooks === "object" && hooks !== null) {
      const hookMap = hooks as Record<string, unknown>;
      for (const event of CLAUDE_HOOK_EVENTS) {
        const groups = Array.isArray(hookMap[event]) ? (hookMap[event] as ClaudeHookGroup[]) : [];
        const next = groups
          .map((group) => ({
            ...group,
            hooks: (group?.hooks ?? []).filter((h) => !isLlmBudgetEntry(h)),
          }))
          .filter((group) => group.hooks.length > 0);
        if (next.length !== groups.length) removedFrom = settingsPath;
        if (next.length === 0) delete hookMap[event];
        else hookMap[event] = next;
      }
      writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    }
  }

  if (existsSync(wrapper)) {
    // Wrapper is regenerated by install; leave bin dir alone (shim lives there).
  }
  return removedFrom
    ? `Removed llm-budget entries from ${removedFrom}\n`
    : "No llm-budget hook entries found.\n";
}
