import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  asJsonArray,
  asJsonObject,
  emptyJsonObject,
  parseJsonText,
  type JsonArray,
  type JsonValue,
} from "../json-value.js";
import { ensureLlmConfig } from "./config.js";
import { claudeHookWrapperPath, claudeSettingsPath } from "./paths.js";

/** Hook events the guard registers (enforce set only — see claude-hook.ts). */
const CLAUDE_HOOK_EVENTS = ["UserPromptSubmit", "PreToolUse"] as const;

function isLlmBudgetEntry(entry: JsonValue): boolean {
  const obj = asJsonObject(entry);
  if (!obj || !("command" in obj)) return false;
  return String(obj.command).includes("llm-budget");
}

function groupHooks(group: JsonValue): JsonArray {
  const obj = asJsonObject(group);
  return asJsonArray(obj?.hooks) ?? [];
}

/**
 * Register the guard into `~/.claude/settings.json`.
 *
 * settings.json holds unrelated user config, so this merges carefully: only
 * `hooks.<event>` lists gain (or keep) one entry whose command references
 * llm-budget. Everything else is preserved verbatim.
 */
export function installClaudeHooks(home = homedir()): string {
  ensureLlmConfig(home);
  const wrapper = claudeHookWrapperPath(home);
  const settingsPath = claudeSettingsPath(home);
  const cli = join(fileURLToPath(new URL("./cli.js", import.meta.url)));

  mkdirSync(dirname(wrapper), { recursive: true });
  writeFileSync(
    wrapper,
    `#!/bin/bash
NODE="$(command -v node 2>/dev/null || true)"
if [ -z "$NODE" ]; then
  for candidate in "$HOME/.vite-plus/bin/node" /usr/bin/node /usr/local/bin/node; do
    if [ -x "$candidate" ]; then
      NODE="$candidate"
      break
    fi
  done
fi
if [ -z "$NODE" ]; then
  # Fail closed: without node we cannot evaluate, so block with instructions.
  echo "llm-budget: node not found; cannot check budget" >&2
  exit 2
fi
exec "$NODE" ${JSON.stringify(cli)} claude hook
`,
  );
  chmodSync(wrapper, 0o755);

  let settings = emptyJsonObject();
  if (existsSync(settingsPath)) {
    settings = asJsonObject(parseJsonText(readFileSync(settingsPath, "utf8"))) ?? emptyJsonObject();
  }
  const hooks = asJsonObject(settings.hooks) ?? emptyJsonObject();

  for (const event of CLAUDE_HOOK_EVENTS) {
    const groups = asJsonArray(hooks[event]) ?? [];
    const already = groups.some((group) => groupHooks(group).some(isLlmBudgetEntry));
    if (!already) {
      const group = emptyJsonObject();
      group.hooks = [{ type: "command", command: wrapper }];
      if (event === "PreToolUse") group.matcher = "*";
      groups.push(group);
    }
    hooks[event] = groups;
  }
  settings.hooks = hooks;

  mkdirSync(dirname(settingsPath), { recursive: true });
  writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  return [
    "Installed llm-budget Claude Code hooks (fail-closed)",
    `  ${settingsPath}`,
    `  ${wrapper}`,
    "",
    "Restart any running Claude Code sessions so they pick up settings.json.",
  ].join("\n");
}

export function uninstallClaudeHooks(home = homedir()): string {
  const wrapper = claudeHookWrapperPath(home);
  const settingsPath = claudeSettingsPath(home);

  let removedFrom = "";
  if (existsSync(settingsPath)) {
    const settings = asJsonObject(parseJsonText(readFileSync(settingsPath, "utf8")));
    const hookMap = asJsonObject(settings?.hooks);
    if (settings && hookMap) {
      for (const event of CLAUDE_HOOK_EVENTS) {
        const groups = asJsonArray(hookMap[event]) ?? [];
        const next: JsonArray = [];
        for (const group of groups) {
          const groupObj = asJsonObject(group) ?? emptyJsonObject();
          const filtered = groupHooks(group).filter((h) => !isLlmBudgetEntry(h));
          if (filtered.length === 0) continue;
          next.push({ ...groupObj, hooks: filtered });
        }
        if (next.length !== groups.length) removedFrom = settingsPath;
        if (next.length === 0) delete hookMap[event];
        else hookMap[event] = next;
      }
      settings.hooks = hookMap;
      writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    }
  }

  if (existsSync(wrapper)) {
    // Wrapper is regenerated by install; leave bin dir alone (shim lives there).
  }
  return removedFrom
    ? `Removed llm-budget entries from ${removedFrom}\n`
    : "No llm-budget hook entries found.\n";
}

export function claudeHooksInstalled(home = homedir()): boolean {
  const settingsPath = claudeSettingsPath(home);
  if (!existsSync(settingsPath)) return false;
  try {
    const settings = asJsonObject(parseJsonText(readFileSync(settingsPath, "utf8")));
    const hooks = asJsonObject(settings?.hooks);
    if (!hooks) return false;
    return CLAUDE_HOOK_EVENTS.every((event) => {
      const groups = asJsonArray(hooks[event]) ?? [];
      return groups.some((group) => groupHooks(group).some(isLlmBudgetEntry));
    });
  } catch {
    return false;
  }
}
